#!/usr/bin/env bash
# herdr-brain installer — optional systemd user unit + stable environment file.
#
# Usage: deploy/install.sh [--generate-only]
#
# The unit is GENERATED, never committed: values discovered here (install
# location, python, herdr binary, tts-plugin home, port, env file) are
# substituted into deploy/herdr-brain.service.tmpl and written to
# ~/.config/systemd/user/herdr-brain.service. Any placeholder left
# unsubstituted aborts the install before anything is changed.
#
#   --generate-only   render and write the unit, then stop: no environment
#                     file, no port handling, no systemctl calls.
#
# Idempotent: safe to re-run. On upgrade only the unit this installer owns is
# replaced (stop -> regenerate -> reload -> restart); a unit file we did not
# generate is never overwritten. A listener on the port is only ever stopped
# when it is provably ours (see `bin/herdr-brain _claim-port`).
#
# SECRETS DISCIPLINE: GLM_API_KEY is taken from this process's environment
# and written to ~/.config/herdr-brain/env (outside the repo, mode 600). The
# value is NEVER echoed, printed, logged or passed on a command line. Do not
# add `set -x` here.
set -euo pipefail

# Keep `&` in a substituted value literal on bash >= 5.2.
shopt -u patsub_replacement 2>/dev/null || true

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LAUNCHER="$REPO_DIR/bin/herdr-brain"
UNIT_NAME="herdr-brain.service"
UNIT_TMPL="$REPO_DIR/deploy/herdr-brain.service.tmpl"
UNIT_DST="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/$UNIT_NAME"
ENV_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/herdr-brain"
ENV_FILE="$ENV_DIR/env"
UNIT_MARKER="# herdr-brain-managed: generated by deploy/install.sh from herdr-brain.service.tmpl; local edits are overwritten on upgrade."
LEGACY_SIGNATURE="Description=Herdr Brain (voice PWA backend)"

GENERATE_ONLY=0

log() { printf '[install] %s\n' "$*"; }
warn() { printf '[install] WARNING: %s\n' "$*" >&2; }
die() { printf '[install] ERROR: %s\n' "$*" >&2; exit 1; }

for arg in "$@"; do
  case "$arg" in
    --generate-only) GENERATE_ONLY=1 ;;
    -h|--help) sed -n '2,6p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown argument: $arg (usage: deploy/install.sh [--generate-only])" ;;
  esac
done

[[ -f "$UNIT_TMPL" ]] || die "missing $UNIT_TMPL (run this script from a herdr-brain checkout)."
[[ -x "$LAUNCHER" ]] || die "missing $LAUNCHER (run this script from a herdr-brain checkout)."
if [[ "$GENERATE_ONLY" != 1 ]]; then
  [[ -x "$REPO_DIR/.venv/bin/python" ]] || die "missing $REPO_DIR/.venv — run scripts/bootstrap.sh first."
fi

# ---------------------------------------------------------- discover values
# One resolver surface: the launcher's portable resolvers (design Decision 4/5).
INSTALL_DIR="$REPO_DIR"
PYTHON="$REPO_DIR/.venv/bin/python"
ENV_FILE_PATH="$ENV_FILE"
PORT="$("$LAUNCHER" _resolve port)" || die "cannot resolve the port."
TTS_HOME="$("$LAUNCHER" _resolve tts-home)" || die "cannot resolve the tts-plugin home (see the message above)."
HERDR_BIN_FOUND="$("$LAUNCHER" _resolve bin)" || die "cannot resolve the herdr binary."
# The resolver ends in a bare `herdr`; a unit cannot rely on the minimal
# systemd PATH, so an unresolved binary is a hard failure here.
if [[ "$HERDR_BIN_FOUND" != /* ]]; then
  die "cannot locate the herdr binary. Install herdr, put it on PATH, or export HERDR_BIN=/absolute/path/to/herdr and re-run."
fi
[[ -x "$HERDR_BIN_FOUND" ]] || die "HERDR_BIN=$HERDR_BIN_FOUND is not executable; fix it or export HERDR_BIN=/absolute/path/to/herdr."

# ------------------------------------------------------------ render unit
# systemd expands %-specifiers and $-variables and splits ExecStart on
# whitespace, so values containing those characters cannot be represented.
check_unit_safe() { # $1 = placeholder name, $2 = value
  if [[ "$2" =~ [[:space:]%\$\"\\] ]]; then
    die "$1 value '$2' contains whitespace or one of % \$ \" \\ and cannot be represented in a systemd unit; install under a path without them."
  fi
}
for pair in "INSTALL_DIR:$INSTALL_DIR" "PYTHON:$PYTHON" "HERDR_BIN:$HERDR_BIN_FOUND" \
            "TTS_HOME:$TTS_HOME" "PORT:$PORT" "ENV_FILE:$ENV_FILE_PATH"; do
  check_unit_safe "${pair%%:*}" "${pair#*:}"
done

rendered="$(cat "$UNIT_TMPL")"
rendered="${rendered//@INSTALL_DIR@/$INSTALL_DIR}"
rendered="${rendered//@PYTHON@/$PYTHON}"
rendered="${rendered//@HERDR_BIN@/$HERDR_BIN_FOUND}"
rendered="${rendered//@TTS_HOME@/$TTS_HOME}"
rendered="${rendered//@PORT@/$PORT}"
rendered="${rendered//@ENV_FILE@/$ENV_FILE_PATH}"
rendered="$UNIT_MARKER"$'\n'"$rendered"

leftover="$(printf '%s\n' "$rendered" | grep -oE '@[A-Z][A-Z_]*@' | sort -u | tr '\n' ' ' || true)"
if [[ -n "$leftover" ]]; then
  die "the generated unit still contains unsubstituted placeholders: ${leftover}— nothing was written."
fi

# Only a unit this installer generated (marker) or the legacy static unit it
# replaces may be overwritten; anything else at that path is not ours.
unit_is_ours() {
  [[ -f "$UNIT_DST" ]] || return 0
  grep -qF "# herdr-brain-managed:" "$UNIT_DST" 2>/dev/null && return 0
  grep -qxF "$LEGACY_SIGNATURE" "$UNIT_DST" 2>/dev/null
}
unit_is_ours || die "$UNIT_DST exists but was not generated by this installer; refusing to overwrite it. Move it aside and re-run."

unit_current() { [[ -f "$UNIT_DST" ]] && [[ "$(cat "$UNIT_DST")" == "$rendered" ]]; }

write_unit() {
  local tmp
  mkdir -p "$(dirname "$UNIT_DST")"
  tmp="$(mktemp "$(dirname "$UNIT_DST")/.herdr-brain.service.XXXXXX")"
  printf '%s\n' "$rendered" > "$tmp"
  chmod 644 "$tmp"
  mv -f "$tmp" "$UNIT_DST"
}

if [[ "$GENERATE_ONLY" == 1 ]]; then
  if unit_current; then
    log "Unit already up to date: $UNIT_DST"
  else
    write_unit
    log "Generated $UNIT_DST (no systemd calls made)."
  fi
  exit 0
fi

command -v systemctl >/dev/null 2>&1 \
  || die "systemctl not found. The systemd route is optional; on systems without systemd use the plugin startup route instead."

# ------------------------------------------------------- port ownership
# Audit C5: a listener on the port is only ever stopped when it is provably
# ours (our pidfile, or the systemd unit's MainPID, which is left for the
# unit restart below). A foreign process aborts the install untouched; the
# policy lives once in bin/herdr-brain and is shared with the daemon.
port_listener_pid() {
  ss -tlnp "sport = :$PORT" 2>/dev/null | grep -oE 'pid=[0-9]+' | head -n1 | cut -d= -f2 || true
}

HERDR_BRAIN_PORT="$PORT" "$LAUNCHER" _claim-port installer \
  || die "port $PORT is held by a process this installation does not own (see above); the installer leaves it untouched."

# ---------------------------------------------------------------- env file
mkdir -p "$ENV_DIR"
chmod 700 "$ENV_DIR"
env_changed=0

if [[ ! -f "$ENV_FILE" ]]; then
  ( umask 077
    printf '# Generated by herdr-brain deploy/install.sh — do not commit.\n# Add: GLM_API_KEY=<your key>   (this file must stay mode 600)\n' > "$ENV_FILE" )
  chmod 600 "$ENV_FILE"
  env_changed=1
  log "Created $ENV_FILE (mode 600)."
fi

env_has_key() { # exact-line check without putting the secret on a command line
  local line
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" == "GLM_API_KEY=${GLM_API_KEY:-}" ]] && return 0
  done < "$ENV_FILE"
  return 1
}

if [[ -n "${GLM_API_KEY:-}" ]]; then
  [[ "$GLM_API_KEY" != *$'\n'* && "$GLM_API_KEY" != *$'\r'* ]] || die "GLM_API_KEY must be a single line."
  if env_has_key; then
    log "$ENV_FILE already holds this key."
  else
    # Merge via a same-directory temp file + mv so a crash never leaves a partial env.
    tmp_env="$(mktemp "$ENV_DIR/env.XXXXXX")"
    trap 'rm -f "$tmp_env"' EXIT
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ "$line" == GLM_API_KEY=* ]] || printf '%s\n' "$line"
    done < "$ENV_FILE" > "$tmp_env"
    printf 'GLM_API_KEY=%s\n' "$GLM_API_KEY" >> "$tmp_env"
    chmod 600 "$tmp_env"
    mv -f "$tmp_env" "$ENV_FILE"
    trap - EXIT
    env_changed=1
    log "Wrote the key to $ENV_FILE (mode 600; the value is not shown)."
  fi
elif ! grep -q '^GLM_API_KEY=' "$ENV_FILE" 2>/dev/null; then
  warn "no GLM_API_KEY found: /ask will answer 503 until you add it to $ENV_FILE (or export GLM_API_KEY and re-run this installer)."
fi

# ------------------------------------------------------------ unit install
unit_changed=0
unit_active=0
systemctl --user is-active --quiet "$UNIT_NAME" 2>/dev/null && unit_active=1

if unit_current; then
  log "The unit is already installed and up to date."
else
  if [[ "$unit_active" == 1 && -f "$UNIT_DST" ]]; then
    log "Stopping the running unit before regenerating it…"
    systemctl --user stop "$UNIT_NAME"
    unit_active=0
  fi
  write_unit
  unit_changed=1
  log "Generated the unit at $UNIT_DST."
fi

systemctl --user daemon-reload
loginctl enable-linger "${USER:-$(id -un)}" 2>/dev/null || true   # survives WSL reloads with no login session
systemctl --user enable "$UNIT_NAME" >/dev/null
if [[ "$unit_changed" == 1 || "$env_changed" == 1 || "$unit_active" == 0 ]]; then
  log "(Re)starting the unit so it picks up the current unit and environment…"
  systemctl --user restart "$UNIT_NAME"
fi
log "Unit enabled (auto-start + linger)."

# ------------------------------------------------------------ health gate
# /health alone can false-pass while a STRAY process still owns the port,
# so also prove the unit's own process is the listener before declaring victory.
HEALTH_URL="http://127.0.0.1:$PORT/health"
log "Checking $HEALTH_URL (up to 10s)…"
healthy=0
for _ in $(seq 1 20); do
  if curl -fsS -m 2 "$HEALTH_URL" >/dev/null 2>&1; then
    unit_main_pid="$(systemctl --user show -P MainPID --value "$UNIT_NAME" 2>/dev/null || true)"
    if [[ -n "$unit_main_pid" && "$unit_main_pid" != "0" && "$(port_listener_pid)" == "$unit_main_pid" ]]; then
      healthy=1
      break
    fi
  fi
  sleep 0.5
done

if [[ "$healthy" != 1 ]]; then
  log "FAILED: the service did not answer /health within 10s. Last journal lines:"
  journalctl --user -u herdr-brain -n 30 --no-pager || true
  exit 1
fi

log "Health: $(curl -fsS -m 2 "$HEALTH_URL")"
log "Done: systemctl --user status herdr-brain"
