# Scenario 7: reinstall-idempotent (AT-11 slice 14, task 2.6; level V2, M2).
#
# PRD scenario "Reinstalación idempotente": a full install, then a full
# re-run — user state (env-file content, preferences) is preserved, and a
# broken install is repaired by the re-run without destroying user state.
#
# Local installation/state proof only. The wizard and keymap now run with
# a real interpreter. HTTP/herdr and the forbidden systemd boundary use
# explicit external doubles; this is NOT real-service state evidence.
#
#   - deploy/install.sh --generate-only re-run idempotence (unit stable)
#   - broken-install repair: a marker-bearing corrupted unit, and a deleted
#     unit with user state present, are regenerated byte-identically
#   - refusal to overwrite a foreign (user-owned) unit — user state the
#     installer must never destroy
#   - full-route state preservation up to the systemd boundary: the
#     mode-600 env file keeps its comments and unknown keys across a key
#     merge and across a no-op re-run; the persisted port preference
#     (config.env) is honored in the unit and never rewritten
#
# The full route MUST stop at the doubled `systemctl --user daemon-reload`
# (exit 78, no real bus contacted). Every assertion targets the stages that
# complete before that boundary; the boundary itself is recorded as an
# observed fact, never hidden and never claimed as a service state.
# Keymap and marker preservation are checked below; live services are NOT claimed.
#
# Pure bash on purpose: the sandbox PATH allowlist has no grep/sed/stat.
# python3 (allowlisted) checks the env-file mode — bash cannot see the
# group/other permission bits.

HERDR_SCENARIO4_API=1 source "$CHECKOUT/scripts/acceptance/scenarios/04-first-run-keys.sh"
onboarding_sandbox
# No host listener probe or systemd call is authorized in this assignment.
"$ONBOARDING_PYTHON" - "$SCEN_DIR" <<'PY'
import pathlib, sys
root = pathlib.Path(sys.argv[1])
bin = root / 'bin'; bin.mkdir()
(bin / 'herdr').symlink_to(root / 'herdr-double')
for name, body in {
    'lsof': 'exit 1',
    'systemctl': "echo 'TEST-DOUBLE: systemd boundary (no real bus)' >&2; exit 78",
}.items():
    path = bin / name; path.write_text('#!/bin/sh\n' + body + '\n'); path.chmod(0o755)
PY
export PATH="$SCEN_DIR/bin:$PATH"
BRAIN="$CHECKOUT/hosts/herdr/brain"
INSTALLER="$BRAIN/deploy/install.sh"
UNIT_DST="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/herdr-brain.service"
ENV_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/herdr-brain"
ENV_FILE="$ENV_DIR/env"
PREF_FILE="$ENV_DIR/config.env"
PORT_PREF=18741          # persisted preference under test (seeded, never exported)
KEY_OLD="scen7-old-key"  # seeded credential value; never printed by an assertion
KEY_NEW="scen7-new-key"

nbad=0
fail() { bad "$1"; nbad=$((nbad + 1)); }

# Deterministic non-interactive stdin for every child of this scenario.
exec 0</dev/null

# run_install <log-stem> <argv...> — a step() with one log per invocation,
# so consecutive runs compare precisely. argv is logged redacted: the GLM
# key value never reaches cmd.log.
run_install() {
  local stem=$1; shift
  redact_argv "$@" >> "$SCEN_DIR/cmd.log"
  "$@" > "$SCEN_DIR/$stem.log" 2>&1
}

# --- host prerequisites (derived, never hardcoded) -------------------------
# herdr: the installer requires an absolute executable (the unit's HERDR_BIN);
# python3: the env-file mode check; systemctl: the full route's boundary
# precondition (the --generate-only phases do not need it). A missing tool
# is a missing prerequisite — never stubbed.
HERDR_BIN_RESOLVED=""
IFS=: read -r -a _pdirs <<< "$PATH"
for _d in "${_pdirs[@]}"; do
  [[ -n $_d && -x "$_d/herdr" ]] && { HERDR_BIN_RESOLVED="$_d/herdr"; break; }
done
_missing=""
[[ -n $HERDR_BIN_RESOLVED ]] || _missing="herdr (absolute binary required by the unit)"
command -v python3 >/dev/null 2>&1 || _missing="${_missing:+$_missing; }python3 (env-file mode check)"
command -v systemctl >/dev/null 2>&1 || _missing="${_missing:+$_missing; }systemctl (full-route boundary precondition)"
[[ -z $_missing ]] || block "host prerequisite unavailable: $_missing"
export HERDR_BIN="$HERDR_BIN_RESOLVED"

mode600() { # mode600 <file> — octal permission check via allowlisted python3
  python3 - "$1" <<'PY'
import os, sys
sys.exit(0 if oct(os.stat(sys.argv[1]).st_mode & 0o777) == "0o600" else 1)
PY
}

env_key_line_count() { # GLM_API_KEY lines in the env file
  local n=0 line
  while IFS= read -r line || [[ -n $line ]]; do
    [[ $line == GLM_API_KEY=* ]] && n=$((n + 1))
  done < "$ENV_FILE"
  printf '%s' "$n"
}

env_key_value() { # value part of the first GLM_API_KEY line (empty if absent)
  local line
  while IFS= read -r line || [[ -n $line ]]; do
    [[ $line == GLM_API_KEY=* ]] && { printf '%s' "${line#GLM_API_KEY=}"; return; }
  done < "$ENV_FILE"
}

env_user_state() { # the env file minus the GLM key line — what must survive
  local line
  while IFS= read -r line || [[ -n $line ]]; do
    [[ $line == GLM_API_KEY=* ]] || printf '%s\n' "$line"
  done < "$ENV_FILE"
}

# --- repo shape + persisted-preference seed --------------------------------
[[ -f $INSTALLER && -x $BRAIN/bin/herdr-brain && -f $BRAIN/deploy/herdr-brain.service.tmpl ]] \
  || fail "repo shape: installer, launcher or template missing under \$CHECKOUT/hosts/herdr/brain"
mkdir -p "$ENV_DIR"
printf 'HERDR_BRAIN_PORT=%s\n' "$PORT_PREF" > "$PREF_FILE"
pref_seed=$(<"$PREF_FILE")

# --- Phase 1: first --generate-only run writes the unit --------------------
rc=0; run_install gen1 bash "$INSTALLER" --generate-only || rc=$?
if [[ $rc -eq 0 && -f $UNIT_DST ]]; then
  ok "generate-only: first run exits 0 and writes the unit at ${UNIT_DST#"$HOME"/}"
else
  fail "generate-only: first run failed (rc=$rc; see gen1.log)"
fi
golden=""
[[ -f $UNIT_DST ]] && golden=$(<"$UNIT_DST")
if [[ $golden == "# herdr-brain-managed:"* ]]; then
  ok "generate-only: unit carries the installer ownership marker"
else
  fail "generate-only: unit lacks the herdr-brain-managed marker"
fi
if [[ $golden =~ @[A-Z][A-Z_]*@ ]]; then
  fail "generate-only: unit still contains unsubstituted @PLACEHOLDER@ tokens"
else
  ok "generate-only: no unsubstituted placeholders remain in the rendered unit"
fi
if [[ $golden == *"Environment=HERDR_BRAIN_PORT=$PORT_PREF"* ]]; then
  ok "preferences: unit honors the persisted port preference ($PORT_PREF from config.env)"
else
  fail "preferences: unit does not carry the persisted port preference"
fi
if [[ $golden == *"EnvironmentFile=$ENV_FILE"* ]]; then
  ok "credentials: unit points at the stable env file ($ENV_FILE)"
else
  fail "credentials: unit does not reference the env file"
fi
assert_grep "generate-only: installer reports no systemd calls were made" \
  "no systemd calls made" "$SCEN_DIR/gen1.log" -F

# --- Phase 2: idempotent re-run leaves the unit untouched ------------------
rc=0; run_install gen2 bash "$INSTALLER" --generate-only || rc=$?
if [[ $rc -eq 0 ]]; then
  ok "generate-only re-run: exits 0"
else
  fail "generate-only re-run: rc=$rc (see gen2.log)"
fi
assert_grep "generate-only re-run: reports the unit already up to date" \
  "already up to date" "$SCEN_DIR/gen2.log" -F
if [[ -f $UNIT_DST && $(<"$UNIT_DST") == "$golden" ]]; then
  ok "generate-only re-run: unit byte-identical after the no-op re-run"
else
  fail "generate-only re-run: unit content changed on the no-op re-run"
fi

# --- Phase 3: broken-install repair (corrupted unit, marker survives) ------
printf '%s\n' "# herdr-brain-managed: truncated by an interrupted generation (scenario 7 breakage drill)" > "$UNIT_DST"
rc=0; run_install repair bash "$INSTALLER" --generate-only || rc=$?
assert_grep "repair: corrupted marker-bearing unit regenerated" \
  "Generated" "$SCEN_DIR/repair.log" -F
if [[ $rc -eq 0 && -f $UNIT_DST && $(<"$UNIT_DST") == "$golden" ]]; then
  ok "repair: broken unit repaired byte-identically (rc=0)"
else
  fail "repair: corrupted unit was not restored (rc=$rc; see repair.log)"
fi

# --- Phase 4: a foreign unit is refused, user state untouched --------------
foreign_body='[Unit]
Description=User-owned unit, not managed by this installer'
printf '%s\n' "$foreign_body" > "$UNIT_DST"
rc=0; run_install foreign bash "$INSTALLER" --generate-only || rc=$?
if [[ $rc -ne 0 ]]; then
  ok "refusal: a foreign unit is refused non-zero (rc=$rc)"
else
  fail "refusal: the installer accepted or overwrote a foreign unit with rc=0"
fi
assert_grep "refusal: reason names the ownership rule" \
  "was not generated by this installer" "$SCEN_DIR/foreign.log" -F
if [[ $(<"$UNIT_DST") == "$foreign_body" ]]; then
  ok "refusal: the user-owned unit is left byte-identical"
else
  fail "refusal: the foreign unit was mutated"
fi
rm -f "$UNIT_DST"

# --- Phase 5: full-route state preservation up to the systemd boundary -----
# A REAL interpreter for both preflight and subsequent wizard execution.
"$ONBOARDING_PYTHON" - "$BRAIN" <<'PY'
import pathlib, sys
bin = pathlib.Path(sys.argv[1]) / '.venv/bin'; bin.mkdir(parents=True, exist_ok=True)
python = bin / 'python'
if not python.exists(): python.symlink_to(sys.executable)
PY

# Seed the user state the re-run must preserve: comments, an unknown key,
# and an older credential value. Wizard preservation is exercised afterwards.
( umask 077
  printf '# user comment line\n# another note\nOTHER_TOOL_FLAG=keep-me\nGLM_API_KEY=%s\n' "$KEY_OLD" > "$ENV_FILE" )
chmod 600 "$ENV_FILE"
seed_user_state='# user comment line
# another note
OTHER_TOOL_FLAG=keep-me'

rc1=0; run_install full1 env GLM_API_KEY="$KEY_NEW" bash "$INSTALLER" || rc1=$?
assert_grep "full route: key merge stage reached before the systemd boundary" \
  "Wrote the key to" "$SCEN_DIR/full1.log" -F
assert_grep "full route: unit regenerated before the systemd boundary" \
  "Generated the unit at" "$SCEN_DIR/full1.log" -F
if [[ $rc1 -eq 78 && $(<"$SCEN_DIR/full1.log") == *"TEST-DOUBLE: systemd boundary"* ]]; then
  ok_stubbed "full route stops at the deliberate systemd boundary (exit 78); no service-state claim"
else
  fail "full route did not stop at the declared systemd boundary (rc=$rc1)"
fi
if [[ $(env_key_line_count) -eq 1 && $(env_key_value) == "$KEY_NEW" ]]; then
  ok "credentials: env file holds exactly one GLM_API_KEY line, rotated to the new value"
else
  fail "credentials: GLM_API_KEY not rotated to a single new line (count=$(env_key_line_count))"
fi
if [[ $(env_user_state) == "$seed_user_state" ]]; then
  ok "credentials/preferences: comments and unknown keys preserved byte-identically through the merge"
else
  fail "credentials/preferences: the merge altered the user's non-key lines (see full1.log)"
fi
if mode600 "$ENV_FILE"; then
  ok "credentials: env file stays mode 600 across the merge"
else
  fail "credentials: env file is not mode 600 after the merge"
fi
if [[ -f $UNIT_DST && $(<"$UNIT_DST") == "$golden" ]]; then
  ok "repair: deleted unit regenerated byte-identically while user state stayed intact"
else
  fail "repair: the full route did not restore the deleted unit"
fi
if [[ $(<"$PREF_FILE") == "$pref_seed" ]]; then
  ok "preferences: persisted port preference untouched by the full route"
else
  fail "preferences: config.env was rewritten by the installer"
fi

# --- Phase 6: wizard/keymap/marker preservation through install and repair ---
step "$ONBOARDING_PYTHON" - "$CHECKOUT" <<'PY'
import hashlib, json, os, pathlib, subprocess, sys
root = pathlib.Path(sys.argv[1]); config = pathlib.Path(os.environ['XDG_CONFIG_HOME'])
launcher = root / 'hosts/herdr/brain/bin/herdr-brain'
argv = ['bash', str(launcher), 'first-run', '--non-interactive', '--stt', 'none',
        '--voice-provider', 'piper', '--keymap-style', 'menu', '--json']
result = subprocess.run(argv, capture_output=True, text=True, timeout=30)
assert result.returncode == 0, result.stderr
marker = config / 'herdr-tts/first-run.done'
payload = json.loads(marker.read_text())
assert payload['keymap'] == 'menu' and payload['keymap_reloaded'] is True
assert 'server reload-config' in (pathlib.Path(os.environ['HOME']) / 'herdr.calls').read_text()
paths = [config / 'herdr-brain/env', config / 'herdr-brain/config.env',
         config / 'herdr-tts/config.env', config / 'herdr-tts/keymap.json',
         config / 'herdr/config.toml', marker]
before = {path: (path.read_bytes(), path.stat().st_mode & 0o777) for path in paths}
installer = root / 'hosts/herdr/brain/deploy/install.sh'
for repair in (False, True):
    if repair:
        (config / 'systemd/user/herdr-brain.service').write_text('# herdr-brain-managed: interrupted\n')
    result = subprocess.run(['bash', str(installer), '--generate-only'], capture_output=True, text=True)
    assert result.returncode == 0, result.stderr
    result = subprocess.run(argv, capture_output=True, text=True, timeout=30)
    assert result.returncode == 0 and json.loads(result.stdout)['status'] == 'already-completed'
    assert {path: (path.read_bytes(), path.stat().st_mode & 0o777) for path in paths} == before
snapshot = {str(path): [hashlib.sha256(path.read_bytes()).hexdigest(), path.stat().st_mode & 0o777]
            for path in paths}
(pathlib.Path(os.environ['SCEN_DIR']) / 'wizard-state.json').write_text(json.dumps(snapshot))
print('wizard credentials/preferences/keymap/config/marker preserved through reinstallation and repair')
PY
rc=$?
if (( rc == 0 )); then
  ok_stubbed "wizard/keymap adoption and reload, installer rerun/repair preserve all artifacts; services doubled"
else
  fail "wizard/reinstall preservation failed (exit $rc; see stdout.log)"
fi
env_after_full1=$(<"$ENV_FILE")

# --- Phase 7: full re-run is a no-op for unchanged user state --------------
rc2=0; run_install full2 env GLM_API_KEY="$KEY_NEW" bash "$INSTALLER" || rc2=$?
[[ $rc2 == 78 && $(<"$SCEN_DIR/full2.log") == *"TEST-DOUBLE: systemd boundary"* ]] \
  || fail "full rerun did not stop at the declared systemd boundary (rc=$rc2)"
assert_grep "re-run: key merge is a no-op for an unchanged key" \
  "already holds this key" "$SCEN_DIR/full2.log" -F
assert_grep "re-run: unit left alone when already current" \
  "already installed and up to date" "$SCEN_DIR/full2.log" -F
if [[ $(<"$ENV_FILE") == "$env_after_full1" ]]; then
  ok "idempotence: env file byte-identical across the full re-run"
else
  fail "idempotence: env file changed across the full re-run"
fi
if step "$ONBOARDING_PYTHON" - "$SCEN_DIR/wizard-state.json" <<'PY'
import hashlib, json, pathlib, sys
before = json.loads(pathlib.Path(sys.argv[1]).read_text())
after = {name: [hashlib.sha256(pathlib.Path(name).read_bytes()).hexdigest(),
                pathlib.Path(name).stat().st_mode & 0o777] for name in before}
assert after == before
PY
then
  ok "full installer rerun preserves wizard keymap, marker, credentials and preferences byte-identically"
else
  fail "full installer rerun changed wizard artifacts"
fi
if [[ -f $UNIT_DST && $(<"$UNIT_DST") == "$golden" ]]; then
  ok "idempotence: unit byte-identical across the full re-run"
else
  fail "idempotence: unit changed across the full re-run"
fi
if [[ $(<"$PREF_FILE") == "$pref_seed" ]]; then
  ok "idempotence: persisted port preference still untouched"
else
  fail "idempotence: config.env changed across the re-run"
fi
