# Scenario 7: reinstall-idempotent (AT-11 slice 14, task 2.6; level V2, M2).
#
# PRD scenario "Reinstalación idempotente": a full install, then a full
# re-run — user state (env-file content, preferences) is preserved, and a
# broken install is repaired by the re-run without destroying user state.
#
# SCOPE TODAY (honest limitation, also recorded in apply-progress): the
# first-run wizard does not exist yet (M3 tasks 3.1–3.5), so there is no
# credential-capture step, no keymap step and no completion marker to
# preserve, and the sandbox has no systemd user bus, so live services
# cannot run. What exists NOW and is verified here — entirely offline,
# against the repo under test ($CHECKOUT), with no stubs (ok_stubbed is
# never used) and no network:
#
#   - deploy/install.sh --generate-only re-run idempotence (unit stable)
#   - broken-install repair: a marker-bearing corrupted unit, and a deleted
#     unit with user state present, are regenerated byte-identically
#   - refusal to overwrite a foreign (user-owned) unit — user state the
#     installer must never destroy
#   - full-route state preservation up to the systemd boundary: the
#     mode-600 env file keeps its comments and unknown keys across a key
#     merge and across a no-op re-run; the persisted port preference
#     (config.env) is honored in the unit and never rewritten
#
# The full route is EXPECTED to stop at `systemctl --user daemon-reload`
# (env -i has no user bus). Every assertion targets the stages that
# complete before that boundary; the boundary itself is recorded as an
# observed fact, never hidden and never claimed as a service state.
# Keymap, completion marker and live-service state await M3/M4 and are
# NOT claimed here.
#
# Pure bash on purpose: the sandbox PATH allowlist has no grep/sed/stat.
# python3 (allowlisted) checks the env-file mode — bash cannot see the
# group/other permission bits.

BRAIN="$CHECKOUT/hosts/herdr/brain"
INSTALLER="$BRAIN/deploy/install.sh"
UNIT_DST="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/herdr-brain.service"
ENV_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/herdr-brain"
ENV_FILE="$ENV_DIR/env"
PREF_FILE="$ENV_DIR/config.env"
PORT_PREF=18741          # persisted preference under test (seeded, never exported)
KEY_OLD="scen7-old-key"  # seeded credential value; never printed by an assertion
KEY_NEW="scen7-new-key"

nbad=0
fail() { bad "$1"; nbad=$((nbad + 1)); }

# Deterministic non-interactive stdin for every child of this scenario.
exec 0</dev/null

# run_install <log-stem> <argv...> — a step() with one log per invocation,
# so consecutive runs compare precisely. argv is logged redacted: the GLM
# key value never reaches cmd.log.
run_install() {
  local stem=$1; shift
  redact_argv "$@" >> "$SCEN_DIR/cmd.log"
  "$@" > "$SCEN_DIR/$stem.log" 2>&1
}

# --- host prerequisites (derived, never hardcoded) -------------------------
# herdr: the installer requires an absolute executable (the unit's HERDR_BIN);
# python3: the env-file mode check; systemctl: the full route's boundary
# precondition (the --generate-only phases do not need it). A missing tool
# is a missing prerequisite — never stubbed.
HERDR_BIN_RESOLVED=""
IFS=: read -r -a _pdirs <<< "$PATH"
for _d in "${_pdirs[@]}"; do
  [[ -n $_d && -x "$_d/herdr" ]] && { HERDR_BIN_RESOLVED="$_d/herdr"; break; }
done
_missing=""
[[ -n $HERDR_BIN_RESOLVED ]] || _missing="herdr (absolute binary required by the unit)"
command -v python3 >/dev/null 2>&1 || _missing="${_missing:+$_missing; }python3 (env-file mode check)"
command -v systemctl >/dev/null 2>&1 || _missing="${_missing:+$_missing; }systemctl (full-route boundary precondition)"
[[ -z $_missing ]] || block "host prerequisite unavailable: $_missing"
export HERDR_BIN="$HERDR_BIN_RESOLVED"

mode600() { # mode600 <file> — octal permission check via allowlisted python3
  python3 - "$1" <<'PY'
import os, sys
sys.exit(0 if oct(os.stat(sys.argv[1]).st_mode & 0o777) == "0o600" else 1)
PY
}

env_key_line_count() { # GLM_API_KEY lines in the env file
  local n=0 line
  while IFS= read -r line || [[ -n $line ]]; do
    [[ $line == GLM_API_KEY=* ]] && n=$((n + 1))
  done < "$ENV_FILE"
  printf '%s' "$n"
}

env_key_value() { # value part of the first GLM_API_KEY line (empty if absent)
  local line
  while IFS= read -r line || [[ -n $line ]]; do
    [[ $line == GLM_API_KEY=* ]] && { printf '%s' "${line#GLM_API_KEY=}"; return; }
  done < "$ENV_FILE"
}

env_user_state() { # the env file minus the GLM key line — what must survive
  local line
  while IFS= read -r line || [[ -n $line ]]; do
    [[ $line == GLM_API_KEY=* ]] || printf '%s\n' "$line"
  done < "$ENV_FILE"
}

# --- repo shape + persisted-preference seed --------------------------------
[[ -f $INSTALLER && -x $BRAIN/bin/herdr-brain && -f $BRAIN/deploy/herdr-brain.service.tmpl ]] \
  || fail "repo shape: installer, launcher or template missing under \$CHECKOUT/hosts/herdr/brain"
mkdir -p "$ENV_DIR"
printf 'HERDR_BRAIN_PORT=%s\n' "$PORT_PREF" > "$PREF_FILE"
pref_seed=$(<"$PREF_FILE")

# --- Phase 1: first --generate-only run writes the unit --------------------
rc=0; run_install gen1 bash "$INSTALLER" --generate-only || rc=$?
if [[ $rc -eq 0 && -f $UNIT_DST ]]; then
  ok "generate-only: first run exits 0 and writes the unit at ${UNIT_DST#"$HOME"/}"
else
  fail "generate-only: first run failed (rc=$rc; see gen1.log)"
fi
golden=""
[[ -f $UNIT_DST ]] && golden=$(<"$UNIT_DST")
if [[ $golden == "# herdr-brain-managed:"* ]]; then
  ok "generate-only: unit carries the installer ownership marker"
else
  fail "generate-only: unit lacks the herdr-brain-managed marker"
fi
if [[ $golden =~ @[A-Z][A-Z_]*@ ]]; then
  fail "generate-only: unit still contains unsubstituted @PLACEHOLDER@ tokens"
else
  ok "generate-only: no unsubstituted placeholders remain in the rendered unit"
fi
if [[ $golden == *"Environment=HERDR_BRAIN_PORT=$PORT_PREF"* ]]; then
  ok "preferences: unit honors the persisted port preference ($PORT_PREF from config.env)"
else
  fail "preferences: unit does not carry the persisted port preference"
fi
if [[ $golden == *"EnvironmentFile=$ENV_FILE"* ]]; then
  ok "credentials: unit points at the stable env file ($ENV_FILE)"
else
  fail "credentials: unit does not reference the env file"
fi
assert_grep "generate-only: installer reports no systemd calls were made" \
  "no systemd calls made" "$SCEN_DIR/gen1.log" -F

# --- Phase 2: idempotent re-run leaves the unit untouched ------------------
rc=0; run_install gen2 bash "$INSTALLER" --generate-only || rc=$?
if [[ $rc -eq 0 ]]; then
  ok "generate-only re-run: exits 0"
else
  fail "generate-only re-run: rc=$rc (see gen2.log)"
fi
assert_grep "generate-only re-run: reports the unit already up to date" \
  "already up to date" "$SCEN_DIR/gen2.log" -F
if [[ -f $UNIT_DST && $(<"$UNIT_DST") == "$golden" ]]; then
  ok "generate-only re-run: unit byte-identical after the no-op re-run"
else
  fail "generate-only re-run: unit content changed on the no-op re-run"
fi

# --- Phase 3: broken-install repair (corrupted unit, marker survives) ------
printf '%s\n' "# herdr-brain-managed: truncated by an interrupted generation (scenario 7 breakage drill)" > "$UNIT_DST"
rc=0; run_install repair bash "$INSTALLER" --generate-only || rc=$?
assert_grep "repair: corrupted marker-bearing unit regenerated" \
  "Generated" "$SCEN_DIR/repair.log" -F
if [[ $rc -eq 0 && -f $UNIT_DST && $(<"$UNIT_DST") == "$golden" ]]; then
  ok "repair: broken unit repaired byte-identically (rc=0)"
else
  fail "repair: corrupted unit was not restored (rc=$rc; see repair.log)"
fi

# --- Phase 4: a foreign unit is refused, user state untouched --------------
foreign_body='[Unit]
Description=User-owned unit, not managed by this installer'
printf '%s\n' "$foreign_body" > "$UNIT_DST"
rc=0; run_install foreign bash "$INSTALLER" --generate-only || rc=$?
if [[ $rc -ne 0 ]]; then
  ok "refusal: a foreign unit is refused non-zero (rc=$rc)"
else
  fail "refusal: the installer accepted or overwrote a foreign unit with rc=0"
fi
assert_grep "refusal: reason names the ownership rule" \
  "was not generated by this installer" "$SCEN_DIR/foreign.log" -F
if [[ $(<"$UNIT_DST") == "$foreign_body" ]]; then
  ok "refusal: the user-owned unit is left byte-identical"
else
  fail "refusal: the foreign unit was mutated"
fi
rm -f "$UNIT_DST"

# --- Phase 5: full-route state preservation up to the systemd boundary -----
# Bootstrapped-checkout stand-in: the full-route preflight requires
# $REPO_DIR/.venv/bin/python. Nothing executes it (the unit is never started
# in the sandbox); it only lets the real preflight pass so the env-file and
# unit stages run. Scaffolding, not a stubbed assertion — no assertion rides
# on it.
mkdir -p "$BRAIN/.venv/bin"
printf '#!/bin/sh\nstand-in for a bootstrapped checkout (scenario 7 scaffolding)\n' > "$BRAIN/.venv/bin/python"
chmod 0755 "$BRAIN/.venv/bin/python"

# Seed the user state the re-run must preserve: comments, an unknown key,
# and an older credential value. The first-run wizard (M3) does not exist
# yet, so the scenario seeds the documented state itself.
( umask 077
  printf '# user comment line\n# another note\nOTHER_TOOL_FLAG=keep-me\nGLM_API_KEY=%s\n' "$KEY_OLD" > "$ENV_FILE" )
chmod 600 "$ENV_FILE"
seed_user_state='# user comment line
# another note
OTHER_TOOL_FLAG=keep-me'

rc1=0; run_install full1 env GLM_API_KEY="$KEY_NEW" bash "$INSTALLER" || rc1=$?
assert_grep "full route: key merge stage reached before the systemd boundary" \
  "Wrote the key to" "$SCEN_DIR/full1.log" -F
assert_grep "full route: unit regenerated before the systemd boundary" \
  "Generated the unit at" "$SCEN_DIR/full1.log" -F
if [[ $rc1 -ne 0 ]]; then
  ok "boundary: full route stops at the absent systemd user bus (rc=$rc1) after the stages under test — environmental, recorded"
else
  ok "boundary: full route completed rc=0 in this environment (state assertions below still apply)"
fi
if [[ $(env_key_line_count) -eq 1 && $(env_key_value) == "$KEY_NEW" ]]; then
  ok "credentials: env file holds exactly one GLM_API_KEY line, rotated to the new value"
else
  fail "credentials: GLM_API_KEY not rotated to a single new line (count=$(env_key_line_count))"
fi
if [[ $(env_user_state) == "$seed_user_state" ]]; then
  ok "credentials/preferences: comments and unknown keys preserved byte-identically through the merge"
else
  fail "credentials/preferences: the merge altered the user's non-key lines (see full1.log)"
fi
if mode600 "$ENV_FILE"; then
  ok "credentials: env file stays mode 600 across the merge"
else
  fail "credentials: env file is not mode 600 after the merge"
fi
if [[ -f $UNIT_DST && $(<"$UNIT_DST") == "$golden" ]]; then
  ok "repair: deleted unit regenerated byte-identically while user state stayed intact"
else
  fail "repair: the full route did not restore the deleted unit"
fi
if [[ $(<"$PREF_FILE") == "$pref_seed" ]]; then
  ok "preferences: persisted port preference untouched by the full route"
else
  fail "preferences: config.env was rewritten by the installer"
fi
env_after_full1=$(<"$ENV_FILE")

# --- Phase 6: full re-run is a no-op for unchanged user state --------------
rc2=0; run_install full2 env GLM_API_KEY="$KEY_NEW" bash "$INSTALLER" || rc2=$?
assert_grep "re-run: key merge is a no-op for an unchanged key" \
  "already holds this key" "$SCEN_DIR/full2.log" -F
assert_grep "re-run: unit left alone when already current" \
  "already installed and up to date" "$SCEN_DIR/full2.log" -F
if [[ $(<"$ENV_FILE") == "$env_after_full1" ]]; then
  ok "idempotence: env file byte-identical across the full re-run"
else
  fail "idempotence: env file changed across the full re-run"
fi
if [[ -f $UNIT_DST && $(<"$UNIT_DST") == "$golden" ]]; then
  ok "idempotence: unit byte-identical across the full re-run"
else
  fail "idempotence: unit changed across the full re-run"
fi
if [[ $(<"$PREF_FILE") == "$pref_seed" ]]; then
  ok "idempotence: persisted port preference still untouched"
else
  fail "idempotence: config.env changed across the re-run"
fi
